service: chat-app

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-northeast-2
  stage: dev

  environment:
    DOMAIN_NAME: ltrsdvinge.execute-api.${self:provider.region}.amazonaws.com
    TABLE_NAME: ${self:service}-WebSocketConnections
    STAGE: ${self:provider.stage}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - logs:CreateLogGroup
        - logs:CreateLogStream
        - logs:PutLogEvents
        - logs:DescribeLogStreams
        - logs:TagResource
      Resource: "*"
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:DeleteItem
        - dynamodb:GetItem
        - dynamodb:Query
      Resource:
        - arn:aws:dynamodb:${self:provider.region}:*:table/${self:service}-WebSocketConnections
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource:
        - arn:aws:lambda:${self:provider.region}:*:function:${self:service}-*
    - Effect: Allow
      Action:
        - execute-api:ManageConnections
      Resource:
        - arn:aws:execute-api:${self:provider.region}:*:*/*/@connections/*

functions:
  connect:
    name: ${self:service}-connect
    handler: handlers/connect.handler
    events:
      - websocket:
          route: $connect

  disconnect:
    name: ${self:service}-disconnect
    handler: handlers/disconnect.handler
    events:
      - websocket:
          route: $disconnect

  default:
    name: ${self:service}-default
    handler: handlers/default.handler
    events:
      - websocket:
          route: $default

  message:
    name: ${self:service}-message
    handler: handlers/message.handler
    events:
      - websocket:
          route: sendMessage

resources:
  Resources:
    WebSocketConnectionTable: # WebSocket연결 관리할 DynamoDB 테이블
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-WebSocketConnections
        AttributeDefinitions:
          - AttributeName: connectionId
            AttributeType: S
        KeySchema:
          - AttributeName: connectionId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
