service: mail-classification

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-northeast-2
  environment:
    OPENAI_API_KEY: ${ssm:/prod/openAI/api_key}
    QUOTE_ORDER_SNS_TOPIC_ARN: 'arn:aws:sns:ap-northeast-2:481665114066:quote-order' # 주문 SNS ARN
    MAIL_EXTRACTION_SQS_URL: 'https://sqs.ap-northeast-2.amazonaws.com/481665114066/mail-extraction-trigger' # 견적 SQS ARN
    MAIL_SAVE_SQS_URL: 'https://sqs.ap-northeast-2.amazonaws.com/481665114066/mail-save-trigger' # 공통 SQS ARN

  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - 'ssm:GetParameter'
          Resource: 'arn:aws:ssm:ap-northeast-2:481665114066:parameter/prod/openAI/api_key'
        - Effect: 'Allow'
          Action:
            - 'sns:Publish'
          Resource:
            - 'arn:aws:sns:ap-northeast-2:481665114066:mail-processing'
            - 'arn:aws:sns:ap-northeast-2:481665114066:quote-order' # 주문 SNS ARN
        - Effect: 'Allow'
          Action:
            - 'sqs:SendMessage'
          Resource:
            - 'arn:aws:sqs:ap-northeast-2:481665114066:mail-save-trigger' # 공통 SQS ARN
            - 'arn:aws:sqs:ap-northeast-2:481665114066:mail-extraction-trigger' # 견적 SQS ARN

functions:
  mailClassification:
    name: mail-classification
    handler: handler.handler
    layers:
      - arn:aws:lambda:ap-northeast-2:481665114066:layer:langchainLayer:24
      - arn:aws:lambda:ap-northeast-2:481665114066:layer:langgraphLayer:3
    events:
      - sqs:
          arn: arn:aws:sqs:ap-northeast-2:481665114066:file-mail-classification-trigger
      - sqs:
          arn: arn:aws:sqs:ap-northeast-2:481665114066:mail-classification-trigger
      - sqs:
          arn: arn:aws:sqs:ap-northeast-2:481665114066:zip-mail-classification-trigger

package:
  include:
    - node_modules/**
    - handler.js
    - package.json
    - package-lock.json
