service: mail-extraction

provider:
  name: aws
  runtime: python3.12
  region: ap-northeast-2
  environment:
    OPENAI_API_KEY: ${ssm:/prod/openAI/api_key} # SSM Parameter Store에서 참조
    EXTRACT_QUEUE_URL: 'https://sqs.ap-northeast-2.amazonaws.com/481665114066/information-integrity-verification-trigger'

  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - 'ssm:GetParameter' # SSM Parameter Store 접근 권한 추가
          Resource: 'arn:aws:ssm:ap-northeast-2:481665114066:parameter/prod/openAI/api_key'
        - Effect: 'Allow'
          Action:
            - 'sqs:SendMessage'
            - 'sqs:ReceiveMessage'
            - 'sqs:DeleteMessage'
          Resource:
            - 'arn:aws:sqs:ap-northeast-2:481665114066:mail-extraction-trigger'
            - 'arn:aws:sqs:ap-northeast-2:481665114066:information-integrity-verification-trigger'

functions:
  extractEmailData:
    name: mail-extraction
    image:
      uri: 481665114066.dkr.ecr.ap-northeast-2.amazonaws.com/mail-extraction:latest
    events:
      - sqs:
          arn: arn:aws:sqs:ap-northeast-2:481665114066:mail-extraction-trigger
    vpc:
      subnetIds:
        - ${ssm:/network/private-subnet-id}
      securityGroupIds:
        - ${ssm:/network/lambda-security-group-id}
